magazin(ion).
magazin(mihai).
magazin(elena).
editura(istoria).
editura(arheologie).
editura(calatorie).
vinde(ion,istoria).
vinde(mihai,arheologie).
vinde(elena,calatorie).
carte(faraon,istoria).
carte(jules_verne,calatorie).
carte(pyramidas,arheologie).
